### ISSUE TITLE
反馈BUG与建议

### ISSUE THREAD

**Issue by jlhsr** [Blackjack200/MultiworldInventory#3]
BUG
进入别的世界 如果背包是空的 那么背包东西会被带过去
建议：最好像PC端那样 可以设置 “组”
比如世界
 Word1 Word2 用的组1背包
世界skyblock用的组2背包
不设置则使用nk默认背包

**Comment by Blackjack200** [comment]
现在可能修复了，两个pr分别针对两个问题 、
