### ISSUE TITLE
(Question) Can you share .jar file?

### ISSUE THREAD

**Issue by JuChanMin** [Blackjack200/MultiworldInventory#6]
Hello, I am the person who wants this plugin. :)
I was not good at making plugins, so I couldn't turn on the server with the file you uploaded. :c
Can you share the jar file?

**Comment by Superice666** [comment]
> Hello, I am the person who wants this plugin. :)
> I was not good at making plugins, so I couldn't turn on the server with the file you uploaded. :c
> Can you share the jar file?

@JuChanMin Hey, this plugin has not finished yet! But you can use another plugin MutiBackpack. It has the function which MutiworldInventory has and some other functions. You can download here: https://cloudburstmc.org/resources/mutibackpack.529/

**Comment by JuChanMin** [comment]
ooohhhh I saw this now :O

Thanks for letting me know, and I hope your plugin makes smoothly :3
